### ISSUE TITLE
Book theme

### ISSUE THREAD

**Issue by BenGWeeks** [BenGWeeks/TheBitcoinPlaybook#43]
Book theme does not look like T-Minu-15:

https://github.com/bengweeks/t-minus-15

https://github.com/BenGWeeks/T-Minus-15/blob/main/themes/tminus15-theme.yml

https://github.com/BenGWeeks/T-Minus-15/blob/main/.github/workflows/build-book.yml

**Comment by BenGWeeks** [comment]
Please fix @claude

**Comment by BenGWeeks** [comment]
Did you finish this @claude ?

**Comment by BenGWeeks** [comment]
Sorry, here you go @claude 

```

extends: default

labels:
  chapter: Step
  appendix: Resource

page:
  size: [6in, 9in]
  layout: mirror
  margin-top: 0.5in
  margin-bottom: 0.5in
  margin-inner: 0.8in
  margin-outer: 0.4in

chapter:
  font_size: 14
  align: center
  margin_bottom: 1in

base:
  font_size: 10
  line_height_length: 1.2

heading:
  h1_font_size: 14
  h2_font_size: 12
  h3_font_size: 10
  h4_font_size: 9
  h5_font_size: 8
  h1_align: center
  h1_margin_bottom: 1in

lists:
  text_font_size: 9
  marker_font_size: 9
  line_height: 1.2
  item_spacing: 0

role:
  small-list:
    font_size: 8
    line_height: 1.2

table:
  width: 100%
  font_size: 9
  cell_padding: 4
  head:
    font_style: bold
  body:
    font_size: 10
  role:
    xsmall-table:
      font_size: 7
      head:
        font_size: 7
      body:
        font_size: 7

```
